# Generated by Django 5.2.8 on 2025-11-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0002_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
