# Generated by Django 5.2.8 on 2025-11-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0005_alter_profile_password_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
