# Generated by Django 5.2.8 on 2025-11-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0006_alter_profile_password_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_login',
        ),
    ]
