# Generated by Django 5.2.8 on 2025-11-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0007_remove_profile_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
