# Generated by Django 5.2.8 on 2025-11-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0008_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
