# Generated by Django 5.2.8 on 2025-11-22 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0009_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_login',
        ),
    ]
